// <auto-generated />
using System;
using LibraryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryAPI.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260707103227_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Silberschatz",
                            AvailableCopies = 5,
                            Branch = "CSE",
                            Category = "Systems",
                            Description = "",
                            ISBN = "978-1-118-06333-0",
                            Publisher = "Wiley",
                            Title = "Operating System Concepts",
                            TotalCopies = 5,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 2,
                            Author = "CLRS",
                            AvailableCopies = 4,
                            Branch = "CSE",
                            Category = "Algorithms",
                            Description = "",
                            ISBN = "978-0-262-03384-8",
                            Publisher = "MIT Press",
                            Title = "Introduction to Algorithms",
                            TotalCopies = 4,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Gang of Four",
                            AvailableCopies = 3,
                            Branch = "CSE",
                            Category = "Software Eng",
                            Description = "",
                            ISBN = "978-0-201-63361-0",
                            Publisher = "Addison-Wesley",
                            Title = "Design Patterns",
                            TotalCopies = 3,
                            Type = "Reference"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Robert C. Martin",
                            AvailableCopies = 3,
                            Branch = "CSE",
                            Category = "Software Eng",
                            Description = "",
                            ISBN = "978-0-13-235088-4",
                            Publisher = "Pearson",
                            Title = "Clean Code",
                            TotalCopies = 3,
                            Type = "Reference"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Boylestad",
                            AvailableCopies = 4,
                            Branch = "ECE",
                            Category = "Electronics",
                            Description = "",
                            ISBN = "978-0-13-272971-9",
                            Publisher = "Pearson",
                            Title = "Electronic Devices and Circuits",
                            TotalCopies = 4,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Oppenheim",
                            AvailableCopies = 3,
                            Branch = "ECE",
                            Category = "Signal Proc",
                            Description = "",
                            ISBN = "978-0-13-814587-3",
                            Publisher = "Pearson",
                            Title = "Signals and Systems",
                            TotalCopies = 3,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Proakis",
                            AvailableCopies = 2,
                            Branch = "ECE",
                            Category = "Communications",
                            Description = "",
                            ISBN = "978-0-07-295716-7",
                            Publisher = "McGraw-Hill",
                            Title = "Digital Communications",
                            TotalCopies = 2,
                            Type = "Reference"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Hibbeler",
                            AvailableCopies = 4,
                            Branch = "MECH",
                            Category = "Mechanics",
                            Description = "",
                            ISBN = "978-0-13-441189-3",
                            Publisher = "Pearson",
                            Title = "Engineering Mechanics",
                            TotalCopies = 4,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Cengel",
                            AvailableCopies = 3,
                            Branch = "MECH",
                            Category = "Thermodynamics",
                            Description = "",
                            ISBN = "978-0-07-339817-4",
                            Publisher = "McGraw-Hill",
                            Title = "Thermodynamics: An Engineering Approach",
                            TotalCopies = 3,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Frank White",
                            AvailableCopies = 3,
                            Branch = "MECH",
                            Category = "Fluid Mech",
                            Description = "",
                            ISBN = "978-0-07-352934-9",
                            Publisher = "McGraw-Hill",
                            Title = "Fluid Mechanics",
                            TotalCopies = 3,
                            Type = "Reference"
                        },
                        new
                        {
                            Id = 11,
                            Author = "RC Hibbeler",
                            AvailableCopies = 4,
                            Branch = "CIVIL",
                            Category = "Structures",
                            Description = "",
                            ISBN = "978-0-13-479146-4",
                            Publisher = "Pearson",
                            Title = "Structural Analysis",
                            TotalCopies = 4,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 12,
                            Author = "BC Punmia",
                            AvailableCopies = 3,
                            Branch = "CIVIL",
                            Category = "Surveying",
                            Description = "",
                            ISBN = "978-81-7008-354-2",
                            Publisher = "Laxmi Pubs",
                            Title = "Surveying",
                            TotalCopies = 3,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Braja M. Das",
                            AvailableCopies = 2,
                            Branch = "CIVIL",
                            Category = "Geotechnical",
                            Description = "",
                            ISBN = "978-1-305-97093-1",
                            Publisher = "Cengage",
                            Title = "Soil Mechanics",
                            TotalCopies = 2,
                            Type = "Reference"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Stevenson",
                            AvailableCopies = 4,
                            Branch = "EEE",
                            Category = "Power Sys",
                            Description = "",
                            ISBN = "978-0-07-061293-0",
                            Publisher = "McGraw-Hill",
                            Title = "Power Systems Analysis",
                            TotalCopies = 4,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Chapman",
                            AvailableCopies = 3,
                            Branch = "EEE",
                            Category = "Machines",
                            Description = "",
                            ISBN = "978-0-07-338090-2",
                            Publisher = "McGraw-Hill",
                            Title = "Electrical Machines",
                            TotalCopies = 3,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Tanenbaum",
                            AvailableCopies = 3,
                            Branch = "CSE",
                            Category = "Networks",
                            Description = "",
                            ISBN = "978-0-13-212695-3",
                            Publisher = "Pearson",
                            Title = "Computer Networks",
                            TotalCopies = 3,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Silberschatz",
                            AvailableCopies = 4,
                            Branch = "CSE",
                            Category = "Databases",
                            Description = "",
                            ISBN = "978-0-07-352332-3",
                            Publisher = "McGraw-Hill",
                            Title = "Database System Concepts",
                            TotalCopies = 4,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Russell & Norvig",
                            AvailableCopies = 3,
                            Branch = "CSE",
                            Category = "AI/ML",
                            Description = "",
                            ISBN = "978-0-13-468599-1",
                            Publisher = "Pearson",
                            Title = "Artificial Intelligence: A Modern Approach",
                            TotalCopies = 3,
                            Type = "Reference"
                        });
                });

            modelBuilder.Entity("LibraryAPI.Models.BorrowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fine")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowRecords");
                });

            modelBuilder.Entity("LibraryAPI.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("LibraryAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 7, 10, 32, 26, 474, DateTimeKind.Utc).AddTicks(6181),
                            Department = "Administration",
                            Name = "Library Admin",
                            PasswordHash = "$2a$11$C20r6I.rKl6XqivfYBV0regebHHnAAewuMsnChmpr1TC3U3TbR3SG",
                            Phone = "",
                            Role = 1,
                            StudentId = "admin@library.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 7, 10, 32, 26, 701, DateTimeKind.Utc).AddTicks(7109),
                            Department = "CSE",
                            Name = "Arjun Kumar",
                            PasswordHash = "$2a$11$hvTNGHGW0y9HWHTWilE.wObGiAD/EKq4NyIQg2/Ps/Aw7dYn9fO6S",
                            Phone = "",
                            Role = 0,
                            StudentId = "student1@library.com"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 7, 10, 32, 26, 863, DateTimeKind.Utc).AddTicks(9217),
                            Department = "ECE",
                            Name = "Priya Sharma",
                            PasswordHash = "$2a$11$NfYqySiZeH/s3ko8Mg1il.UJ4Q8i6BM9mX7NGBfFOEL/4agYn65nO",
                            Phone = "",
                            Role = 0,
                            StudentId = "student2@library.com"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 7, 10, 32, 27, 23, DateTimeKind.Utc).AddTicks(1191),
                            Department = "MECH",
                            Name = "Rahul Verma",
                            PasswordHash = "$2a$11$3jRfuYURdy9y13kHoUgYZuPxqd1ctScAKk3T1QdeGOlroLGiRB/hW",
                            Phone = "",
                            Role = 0,
                            StudentId = "student3@library.com"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 7, 10, 32, 27, 199, DateTimeKind.Utc).AddTicks(7802),
                            Department = "Library",
                            Name = "Head Librarian",
                            PasswordHash = "$2a$11$w.FnkBs59Z.iXIW1nwBuh.OuOykTKKWMTHf9fsbhOw1wfrQG/6Ih.",
                            Phone = "",
                            Role = 2,
                            StudentId = "librarian@library.com"
                        });
                });

            modelBuilder.Entity("LibraryAPI.Models.BorrowRecord", b =>
                {
                    b.HasOne("LibraryAPI.Models.Book", "Book")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryAPI.Models.User", "User")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryAPI.Models.Reservation", b =>
                {
                    b.HasOne("LibraryAPI.Models.Book", "Book")
                        .WithMany("Reservations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryAPI.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryAPI.Models.Book", b =>
                {
                    b.Navigation("BorrowRecords");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LibraryAPI.Models.User", b =>
                {
                    b.Navigation("BorrowRecords");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
