// <auto-generated />
using System;
using LibraryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryAPI.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Silberschatz",
                            AvailableCopies = 5,
                            Branch = "CSE",
                            Category = "Systems",
                            Description = "",
                            ISBN = "978-1-118-06333-0",
                            Publisher = "Wiley",
                            Title = "Operating System Concepts",
                            TotalCopies = 5,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 2,
                            Author = "CLRS",
                            AvailableCopies = 4,
                            Branch = "CSE",
                            Category = "Algorithms",
                            Description = "",
                            ISBN = "978-0-262-03384-8",
                            Publisher = "MIT Press",
                            Title = "Introduction to Algorithms",
                            TotalCopies = 4,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Gang of Four",
                            AvailableCopies = 3,
                            Branch = "CSE",
                            Category = "Software Eng",
                            Description = "",
                            ISBN = "978-0-201-63361-0",
                            Publisher = "Addison-Wesley",
                            Title = "Design Patterns",
                            TotalCopies = 3,
                            Type = "Reference"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Robert C. Martin",
                            AvailableCopies = 3,
                            Branch = "CSE",
                            Category = "Software Eng",
                            Description = "",
                            ISBN = "978-0-13-235088-4",
                            Publisher = "Pearson",
                            Title = "Clean Code",
                            TotalCopies = 3,
                            Type = "Reference"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Boylestad",
                            AvailableCopies = 4,
                            Branch = "ECE",
                            Category = "Electronics",
                            Description = "",
                            ISBN = "978-0-13-272971-9",
                            Publisher = "Pearson",
                            Title = "Electronic Devices and Circuits",
                            TotalCopies = 4,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Oppenheim",
                            AvailableCopies = 3,
                            Branch = "ECE",
                            Category = "Signal Proc",
                            Description = "",
                            ISBN = "978-0-13-814587-3",
                            Publisher = "Pearson",
                            Title = "Signals and Systems",
                            TotalCopies = 3,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Proakis",
                            AvailableCopies = 2,
                            Branch = "ECE",
                            Category = "Communications",
                            Description = "",
                            ISBN = "978-0-07-295716-7",
                            Publisher = "McGraw-Hill",
                            Title = "Digital Communications",
                            TotalCopies = 2,
                            Type = "Reference"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Hibbeler",
                            AvailableCopies = 4,
                            Branch = "MECH",
                            Category = "Mechanics",
                            Description = "",
                            ISBN = "978-0-13-441189-3",
                            Publisher = "Pearson",
                            Title = "Engineering Mechanics",
                            TotalCopies = 4,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Cengel",
                            AvailableCopies = 3,
                            Branch = "MECH",
                            Category = "Thermodynamics",
                            Description = "",
                            ISBN = "978-0-07-339817-4",
                            Publisher = "McGraw-Hill",
                            Title = "Thermodynamics: An Engineering Approach",
                            TotalCopies = 3,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Frank White",
                            AvailableCopies = 3,
                            Branch = "MECH",
                            Category = "Fluid Mech",
                            Description = "",
                            ISBN = "978-0-07-352934-9",
                            Publisher = "McGraw-Hill",
                            Title = "Fluid Mechanics",
                            TotalCopies = 3,
                            Type = "Reference"
                        },
                        new
                        {
                            Id = 11,
                            Author = "RC Hibbeler",
                            AvailableCopies = 4,
                            Branch = "CIVIL",
                            Category = "Structures",
                            Description = "",
                            ISBN = "978-0-13-479146-4",
                            Publisher = "Pearson",
                            Title = "Structural Analysis",
                            TotalCopies = 4,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 12,
                            Author = "BC Punmia",
                            AvailableCopies = 3,
                            Branch = "CIVIL",
                            Category = "Surveying",
                            Description = "",
                            ISBN = "978-81-7008-354-2",
                            Publisher = "Laxmi Pubs",
                            Title = "Surveying",
                            TotalCopies = 3,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Braja M. Das",
                            AvailableCopies = 2,
                            Branch = "CIVIL",
                            Category = "Geotechnical",
                            Description = "",
                            ISBN = "978-1-305-97093-1",
                            Publisher = "Cengage",
                            Title = "Soil Mechanics",
                            TotalCopies = 2,
                            Type = "Reference"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Stevenson",
                            AvailableCopies = 4,
                            Branch = "EEE",
                            Category = "Power Sys",
                            Description = "",
                            ISBN = "978-0-07-061293-0",
                            Publisher = "McGraw-Hill",
                            Title = "Power Systems Analysis",
                            TotalCopies = 4,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Chapman",
                            AvailableCopies = 3,
                            Branch = "EEE",
                            Category = "Machines",
                            Description = "",
                            ISBN = "978-0-07-338090-2",
                            Publisher = "McGraw-Hill",
                            Title = "Electrical Machines",
                            TotalCopies = 3,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Tanenbaum",
                            AvailableCopies = 3,
                            Branch = "CSE",
                            Category = "Networks",
                            Description = "",
                            ISBN = "978-0-13-212695-3",
                            Publisher = "Pearson",
                            Title = "Computer Networks",
                            TotalCopies = 3,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Silberschatz",
                            AvailableCopies = 4,
                            Branch = "CSE",
                            Category = "Databases",
                            Description = "",
                            ISBN = "978-0-07-352332-3",
                            Publisher = "McGraw-Hill",
                            Title = "Database System Concepts",
                            TotalCopies = 4,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Russell & Norvig",
                            AvailableCopies = 3,
                            Branch = "CSE",
                            Category = "AI/ML",
                            Description = "",
                            ISBN = "978-0-13-468599-1",
                            Publisher = "Pearson",
                            Title = "Artificial Intelligence: A Modern Approach",
                            TotalCopies = 3,
                            Type = "Reference"
                        },
                        new
                        {
                            Id = 19,
                            Author = "F. Scott Fitzgerald",
                            AvailableCopies = 4,
                            Branch = "GENERAL",
                            Category = "Classic",
                            Description = "",
                            ISBN = "978-0743273565",
                            Publisher = "Scribner",
                            Title = "The Great Gatsby",
                            TotalCopies = 4,
                            Type = "Novel"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Harper Lee",
                            AvailableCopies = 3,
                            Branch = "GENERAL",
                            Category = "Classic",
                            Description = "",
                            ISBN = "978-0061120084",
                            Publisher = "Harper",
                            Title = "To Kill a Mockingbird",
                            TotalCopies = 3,
                            Type = "Novel"
                        },
                        new
                        {
                            Id = 21,
                            Author = "George Orwell",
                            AvailableCopies = 5,
                            Branch = "GENERAL",
                            Category = "Dystopian",
                            Description = "",
                            ISBN = "978-0452284234",
                            Publisher = "Signet",
                            Title = "1984",
                            TotalCopies = 5,
                            Type = "Novel"
                        },
                        new
                        {
                            Id = 22,
                            Author = "J.R.R. Tolkien",
                            AvailableCopies = 4,
                            Branch = "GENERAL",
                            Category = "Fantasy",
                            Description = "",
                            ISBN = "978-0547928227",
                            Publisher = "Mariner",
                            Title = "The Hobbit",
                            TotalCopies = 4,
                            Type = "Novel"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Condé Nast",
                            AvailableCopies = 5,
                            Branch = "CSE",
                            Category = "Technology",
                            Description = "",
                            ISBN = "MAG-WIRED-01",
                            Publisher = "Condé Nast",
                            Title = "Wired",
                            TotalCopies = 5,
                            Type = "Magazine"
                        },
                        new
                        {
                            Id = 24,
                            Author = "NG Society",
                            AvailableCopies = 6,
                            Branch = "GENERAL",
                            Category = "Science",
                            Description = "",
                            ISBN = "MAG-NATGEO-02",
                            Publisher = "NG Partners",
                            Title = "National Geographic",
                            TotalCopies = 6,
                            Type = "Magazine"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Time USA",
                            AvailableCopies = 4,
                            Branch = "GENERAL",
                            Category = "News",
                            Description = "",
                            ISBN = "MAG-TIME-03",
                            Publisher = "Time USA",
                            Title = "Time Magazine",
                            TotalCopies = 4,
                            Type = "Magazine"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Forbes Media",
                            AvailableCopies = 3,
                            Branch = "GENERAL",
                            Category = "Business",
                            Description = "",
                            ISBN = "MAG-FORBES-04",
                            Publisher = "Forbes Media",
                            Title = "Forbes",
                            TotalCopies = 3,
                            Type = "Magazine"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Springer Nature",
                            AvailableCopies = 3,
                            Branch = "ECE",
                            Category = "Science",
                            Description = "",
                            ISBN = "MAG-SCIAM-05",
                            Publisher = "Springer",
                            Title = "Scientific American",
                            TotalCopies = 3,
                            Type = "Magazine"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Condé Nast",
                            AvailableCopies = 4,
                            Branch = "GENERAL",
                            Category = "Fashion",
                            Description = "",
                            ISBN = "MAG-VOGUE-06",
                            Publisher = "Condé Nast",
                            Title = "Vogue",
                            TotalCopies = 4,
                            Type = "Magazine"
                        },
                        new
                        {
                            Id = 29,
                            Author = "James Clear",
                            AvailableCopies = 5,
                            Branch = "GENERAL",
                            Category = "Self-Help",
                            Description = "",
                            ISBN = "978-0735211292",
                            Publisher = "Avery",
                            Title = "Atomic Habits",
                            TotalCopies = 5,
                            Type = "Novel"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Frank Herbert",
                            AvailableCopies = 4,
                            Branch = "GENERAL",
                            Category = "Sci-Fi",
                            Description = "",
                            ISBN = "978-0441172719",
                            Publisher = "Ace",
                            Title = "Dune",
                            TotalCopies = 4,
                            Type = "Novel"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Cal Newport",
                            AvailableCopies = 4,
                            Branch = "GENERAL",
                            Category = "Self-Help",
                            Description = "",
                            ISBN = "978-1455586691",
                            Publisher = "Grand Central Publishing",
                            Title = "Deep Work",
                            TotalCopies = 4,
                            Type = "Novel"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Mary Shelley",
                            AvailableCopies = 3,
                            Branch = "GENERAL",
                            Category = "Classic Novel",
                            Description = "",
                            ISBN = "978-0141439471",
                            Publisher = "Penguin Classics",
                            Title = "Frankenstein",
                            TotalCopies = 3,
                            Type = "Novel"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Aldous Huxley",
                            AvailableCopies = 4,
                            Branch = "GENERAL",
                            Category = "Dystopian Novel",
                            Description = "",
                            ISBN = "978-0060850524",
                            Publisher = "Harper Perennial",
                            Title = "Brave New World",
                            TotalCopies = 4,
                            Type = "Novel"
                        },
                        new
                        {
                            Id = 34,
                            Author = "Alex Michaelides",
                            AvailableCopies = 5,
                            Branch = "GENERAL",
                            Category = "Psychological Thriller",
                            Description = "",
                            ISBN = "978-1250301697",
                            Publisher = "Celadon Books",
                            Title = "The Silent Patient",
                            TotalCopies = 5,
                            Type = "Novel"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Eric Matthes",
                            AvailableCopies = 5,
                            Branch = "CSE",
                            Category = "Python Programming",
                            Description = "",
                            ISBN = "978-1593279288",
                            Publisher = "No Starch Press",
                            Title = "Python Crash Course",
                            TotalCopies = 5,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Kyle Simpson",
                            AvailableCopies = 4,
                            Branch = "CSE",
                            Category = "JavaScript",
                            Description = "",
                            ISBN = "978-1092478533",
                            Publisher = "Independently Published",
                            Title = "You Don't Know JS Yet",
                            TotalCopies = 4,
                            Type = "Reference"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Adel S. Sedra",
                            AvailableCopies = 3,
                            Branch = "ECE",
                            Category = "Electronics",
                            Description = "",
                            ISBN = "978-0190853464",
                            Publisher = "Oxford University Press",
                            Title = "Microelectronic Circuits",
                            TotalCopies = 3,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Richard G. Budynas",
                            AvailableCopies = 3,
                            Branch = "MECH",
                            Category = "Mechanical Design",
                            Description = "",
                            ISBN = "978-0073398204",
                            Publisher = "McGraw-Hill Education",
                            Title = "Mechanical Engineering Design",
                            TotalCopies = 3,
                            Type = "Textbook"
                        },
                        new
                        {
                            Id = 39,
                            Author = "J.R.R. Tolkien & David Wenzel",
                            AvailableCopies = 3,
                            Branch = "GENERAL",
                            Category = "Graphic Novel",
                            Description = "",
                            ISBN = "978-0345445261",
                            Publisher = "Del Rey",
                            Title = "The Hobbit: Graphic Novel",
                            TotalCopies = 3,
                            Type = "Novel"
                        },
                        new
                        {
                            Id = 40,
                            Author = "John E. Hopcroft",
                            AvailableCopies = 3,
                            Branch = "CSE",
                            Category = "Formal Languages",
                            Description = "",
                            ISBN = "978-0201441246",
                            Publisher = "Addison-Wesley",
                            Title = "Automata Theory",
                            TotalCopies = 3,
                            Type = "Textbook"
                        });
                });

            modelBuilder.Entity("LibraryAPI.Models.BorrowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fine")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowRecords");
                });

            modelBuilder.Entity("LibraryAPI.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("LibraryAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 9, 11, 48, 52, 630, DateTimeKind.Utc).AddTicks(1577),
                            Department = "Administration",
                            Name = "Library Admin",
                            PasswordHash = "$2a$11$/bLG8bAFBUqKUAK1/2aftejg.1Mud4w3kOeBLqVcqs4WmwH.Zfkha",
                            Phone = "",
                            Role = 1,
                            StudentId = "admin@library.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 9, 11, 48, 52, 899, DateTimeKind.Utc).AddTicks(6773),
                            Department = "CSE",
                            Name = "Arjun Kumar",
                            PasswordHash = "$2a$11$rpiqpfOMHdo.UYi4hfo5DOCvJZBlG2YyKRFzDRt8UPGvt4xAn4Ql.",
                            Phone = "",
                            Role = 0,
                            StudentId = "student1@library.com"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 9, 11, 48, 53, 172, DateTimeKind.Utc).AddTicks(9874),
                            Department = "ECE",
                            Name = "Priya Sharma",
                            PasswordHash = "$2a$11$mtsDQHz1YkU5/ixvxNQXTO/OiCmoRXDBuGCoU/sSkHPJe.c5hSK5S",
                            Phone = "",
                            Role = 0,
                            StudentId = "student2@library.com"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 9, 11, 48, 53, 429, DateTimeKind.Utc).AddTicks(6159),
                            Department = "MECH",
                            Name = "Rahul Verma",
                            PasswordHash = "$2a$11$LxHg45IFudOML15cVwLpbugVn3W6yGtkg5pQWL.90qERM29pZs6KK",
                            Phone = "",
                            Role = 0,
                            StudentId = "student3@library.com"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 9, 11, 48, 53, 737, DateTimeKind.Utc).AddTicks(9996),
                            Department = "Library",
                            Name = "Head Librarian",
                            PasswordHash = "$2a$11$jta99Q0kelfr1y0w6vXJ9u229iTaaM7zbUnrc/83wEEvDiowjyc72",
                            Phone = "",
                            Role = 2,
                            StudentId = "librarian@library.com"
                        });
                });

            modelBuilder.Entity("LibraryAPI.Models.BorrowRecord", b =>
                {
                    b.HasOne("LibraryAPI.Models.Book", "Book")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryAPI.Models.User", "User")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryAPI.Models.Reservation", b =>
                {
                    b.HasOne("LibraryAPI.Models.Book", "Book")
                        .WithMany("Reservations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryAPI.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryAPI.Models.Book", b =>
                {
                    b.Navigation("BorrowRecords");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LibraryAPI.Models.User", b =>
                {
                    b.Navigation("BorrowRecords");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
